on:
  push:
    branches:
      - master
      - dev

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch variables
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=VERSION::$(node .github/scripts/get-version.js)
          
      - name: Show the retrieved branch variables
        run: |
          echo $VERSION
        env:
          VERSION: ${{steps.branch_name.outputs.VERSION}}
          
      - name: Cancel workflow if no version was retrieved
        uses: andymckay/cancel-action@0.2
        if: steps.branch_name.outputs.VERSION == ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install npm dependencies
        run: npm i

      - name: Generate the release file
        run: node .github/scripts/generate-index.js

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.branch_name.outputs.VERSION }}
          release_name: Release v${{ steps.branch_name.outputs.VERSION }}
          body: |
            Sample release ${{ steps.branch_name.outputs.VERSION }}
          draft: ${{ github.ref != 'refs/heads/master' }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.json
          asset_name: release.json
          asset_content_type: application/json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}